version: '3.7'
services:
    crm_admin:
        build:
            context: .
            dockerfile: Dockerfile
        image: EstateVille
        container_name: EstateVille
        restart: always
        ports:
            - '8080:3000'
        environment:
            - VIRTUAL_HOST=${DOMAIN}
            - LETSENCRYPT_HOST=${DOMAIN}
            - VIRTUAL_PORT=8080
        networks:
            - webproxy
networks:
    webproxy:
        external: true
